### ISSUE TITLE
Using CD 2019, would we still see the computation of β involves the γ term of a specific input sentence?

### ISSUE THREAD

**Issue by LinkToPast1990** [INK-USC/hierarchical-explanation#2]
```
        # cd 2019
        rel_hidden = activation(rel_input)  - activation(rel_input - rel_input) # rel_hidden = activation(rel_input) ???
```
![image](https://user-images.githubusercontent.com/13929748/90220504-e6cebf80-de3a-11ea-8c72-625c003b1b80.png)
Referring to ACD paper Eq. 10, it seems now the computation of β does not involve the γ term, right?

**Comment by AuCson** [comment]
Hi LMdeLiangMi,

Thanks for your question. For the decomposition of activation functions, for CD 2019, we won't see computing \beta term involves \gamma term of a specific input sentence. 

Another thing is about the commented out `# rel_hidden = activation(rel_input) ???`. We added the term activation(rel_input - rel_input) because f(0) may not equal to zero for some activation function f. Empirically, we see the code above achieves better performance.
